// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UpworkProject.Services.Database;

#nullable disable

namespace UpworkProject.Services.Migrations
{
    [DbContext(typeof(ProjectDatabaseContext))]
    [Migration("20230930153856_Dynamic Controls Value Store Table designed")]
    partial class DynamicControlsValueStoreTabledesigned
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("UpworkProject.Models.DynamicControls.DynamicControl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ControlIdentity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ControlType")
                        .HasColumnType("int");

                    b.Property<string>("LabelDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionsSerialized")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Options");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DynamicControls", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ControlIdentity = "FullName",
                            ControlType = 0,
                            LabelDate = "What is your name?",
                            OptionsSerialized = "",
                            OrderNumber = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            ControlIdentity = "Gender",
                            ControlType = 2,
                            LabelDate = "What is your gender?",
                            OptionsSerialized = "Male,Female",
                            OrderNumber = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            ControlIdentity = "Hobbies",
                            ControlType = 1,
                            LabelDate = "What is your hobbies?",
                            OptionsSerialized = "Music,Movies,Sports",
                            OrderNumber = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            ControlIdentity = "Country",
                            ControlType = 3,
                            LabelDate = "What is your country name?",
                            OptionsSerialized = "Nepal,India,China,USA,Korea,Japan,Pakistan",
                            OrderNumber = 4,
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            ControlIdentity = "CurrentDateTime",
                            ControlType = 4,
                            LabelDate = "What is your current date time?",
                            OptionsSerialized = "",
                            OrderNumber = 5,
                            Status = 0
                        },
                        new
                        {
                            Id = 6,
                            ControlIdentity = "CurrentDate",
                            ControlType = 5,
                            LabelDate = "What is your current date?",
                            OptionsSerialized = "",
                            OrderNumber = 6,
                            Status = 0
                        },
                        new
                        {
                            Id = 7,
                            ControlIdentity = "CurrentTime",
                            ControlType = 6,
                            LabelDate = "What is your current time?",
                            OptionsSerialized = "",
                            OrderNumber = 7,
                            Status = 0
                        },
                        new
                        {
                            Id = 8,
                            ControlIdentity = "Message",
                            ControlType = 7,
                            LabelDate = "What is your message for us?",
                            OptionsSerialized = "",
                            OrderNumber = 8,
                            Status = 0
                        });
                });

            modelBuilder.Entity("UpworkProject.Models.DynamicControls.ParticipaintInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CurrentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CurrentDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CurrentTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HobbiesSerialized")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Hobbies");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ParticipaintInformations", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
